

export const numero = document.querySelector("#numero") as HTMLInputElement;
export const error = document.querySelector(".error") as HTMLElement;
export const send = document.querySelector("#envoyer") as HTMLInputElement;
export const numeroDes = document.querySelector("#numeroDes") as HTMLInputElement;
export const nomComplet = document.querySelector("#nomComplet") as HTMLInputElement;
export const nomCompletDes = document.querySelector("#nomCompletDes") as HTMLInputElement;
export const fournisseurSelect = document.querySelector("#fournisseur-select") as HTMLSelectElement
export const fournisseurSelect2 = document.querySelector("#fournisseur-select2") as HTMLSelectElement
export const transactionSelect = document.querySelector("#transaction-select") as HTMLSelectElement
export const montant = document.querySelector("#montant") as HTMLInputElement
export const newNomComplet = document.querySelector("#newNomComplet") as HTMLInputElement
export const newTel = document.querySelector("#newTel") as HTMLInputElement
export const adNewClient = document.querySelector("#adNewClient") as HTMLElement
export const numeroCompteAdd = document.querySelector("#numeroCompteAdd") as HTMLInputElement;
export const nomCompletAdd = document.querySelector("#nomCompletAdd") as HTMLInputElement;
export const adNewCompte = document.querySelector("#adNewCompte") as HTMLElement;
export const messageCompte = document.querySelector("#messageCompte") as HTMLElement
export const messageClient = document.querySelector("#messageClient") as HTMLElement;
export const infoG = document.querySelector("#infoG") as HTMLInputElement
export const modalG = document.querySelector("#modalG") as HTMLInputElement
export const des = document.querySelector(".des") as HTMLElement;
export const code = document.querySelector(".code") as HTMLInputElement;
export const codeT = document.querySelector("#codeT") as HTMLInputElement;
export const btnTransaction = document.querySelector(".btnTransaction") as HTMLButtonElement;
export const list_transaction = document.querySelector(".list_transaction") as HTMLDivElement;
export const list_compte = document.querySelector(".list_compte") as HTMLDivElement;
export const btnCompte = document.querySelector(".btnCompte") as HTMLButtonElement;
export const action = document.querySelector(".action") as HTMLElement;
export const bloquer = document.querySelectorAll(".bloquer") as NodeList;
export const debloquer = document.querySelectorAll(".debloquer");
export const colfour = document.querySelectorAll(".colfour");
export const annulerTransa = document.querySelectorAll(".transAnnuler");
export const clientEtat = document.querySelector("#clientEtat") as HTMLElement;
export const clientTransa = document.querySelector("#clientTransa") as HTMLElement;
export const selectFiltre = document.querySelector("#selectFiltre") as HTMLInputElement;
export const infoTransaction=document.querySelector(".infoTransaction") as HTMLElement;
export const mon=document.querySelector("#mon") as HTMLElement;
export const transactionDetail=document.querySelector(".transactionDetail") as HTMLElement;
export const montantRecu=document.querySelector("#montantRecu") as HTMLInputElement;
export const divMontantRecu=document.querySelector("#divMontantRecu") as HTMLElement;
export const port = "http://localhost:8000/api";
